//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using SimpleJSON;


namespace cfg
{ 
   
public sealed partial class Tables
{
    public GameData.TbCharacter TbCharacter {get; }
    public GameData.TbFeature TbFeature {get; }
    public GameData.TbRelic TbRelic {get; }

    public Tables(System.Func<string, JSONNode> loader)
    {
        var tables = new System.Collections.Generic.Dictionary<string, object>();
        TbCharacter = new GameData.TbCharacter(loader("gamedata_tbcharacter")); 
        tables.Add("GameData.TbCharacter", TbCharacter);
        TbFeature = new GameData.TbFeature(loader("gamedata_tbfeature")); 
        tables.Add("GameData.TbFeature", TbFeature);
        TbRelic = new GameData.TbRelic(loader("gamedata_tbrelic")); 
        tables.Add("GameData.TbRelic", TbRelic);
        PostInit();

        TbCharacter.Resolve(tables); 
        TbFeature.Resolve(tables); 
        TbRelic.Resolve(tables); 
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        TbCharacter.TranslateText(translator); 
        TbFeature.TranslateText(translator); 
        TbRelic.TranslateText(translator); 
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}