//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QAssetBundle
{
    
    public class A_png
    {
        public const string BundleName = "a_png";
        public const string A = "a";
    }
    public class Alldiceuipanel_prefab
    {
        public const string BundleName = "alldiceuipanel_prefab";
        public const string ALLDICEUIPANEL = "alldiceuipanel";
    }
    public class Assetobj_1_prefab
    {
        public const string BundleName = "assetobj 1_prefab";
        public const string ASSETOBJ_1 = "assetobj 1";
    }
    public class Assetobj_2_prefab
    {
        public const string BundleName = "assetobj 2_prefab";
        public const string ASSETOBJ_2 = "assetobj 2";
    }
    public class Assetobj_3_prefab
    {
        public const string BundleName = "assetobj 3_prefab";
        public const string ASSETOBJ_3 = "assetobj 3";
    }
    public class Assetobj_prefab
    {
        public const string BundleName = "assetobj_prefab";
        public const string ASSETOBJ = "assetobj";
    }
    public class B_png
    {
        public const string BundleName = "b_png";
        public const string B = "b";
    }
    public class Baguipanel_prefab
    {
        public const string BundleName = "baguipanel_prefab";
        public const string BAGUIPANEL = "baguipanel";
    }
    public class C_png
    {
        public const string BundleName = "c_png";
        public const string C = "c";
    }
    public class Dialoguepanel_prefab
    {
        public const string BundleName = "dialoguepanel_prefab";
        public const string DIALOGUEPANEL = "dialoguepanel";
    }
    public class Imageprefaba_prefab
    {
        public const string BundleName = "imageprefaba_prefab";
        public const string IMAGEPREFABA = "imageprefaba";
    }
    public class Imageprefabb_prefab
    {
        public const string BundleName = "imageprefabb_prefab";
        public const string IMAGEPREFABB = "imageprefabb";
    }
    public class Imageprefabc_prefab
    {
        public const string BundleName = "imageprefabc_prefab";
        public const string IMAGEPREFABC = "imageprefabc";
    }
    public class Iteminfopanel_prefab
    {
        public const string BundleName = "iteminfopanel_prefab";
        public const string ITEMINFOPANEL = "iteminfopanel";
    }
    public class Itemshopinfopanel_prefab
    {
        public const string BundleName = "itemshopinfopanel_prefab";
        public const string ITEMSHOPINFOPANEL = "itemshopinfopanel";
    }
    public class Itemuipanel_prefab
    {
        public const string BundleName = "itemuipanel_prefab";
        public const string ITEMUIPANEL = "itemuipanel";
    }
    public class Pause_prefab
    {
        public const string BundleName = "pause_prefab";
        public const string PAUSE = "pause";
    }
    public class Pieceinfopanel_prefab
    {
        public const string BundleName = "pieceinfopanel_prefab";
        public const string PIECEINFOPANEL = "pieceinfopanel";
    }
    public class Restui_prefab
    {
        public const string BundleName = "restui_prefab";
        public const string RESTUI = "restui";
    }
    public class Rewarduipanel_prefab
    {
        public const string BundleName = "rewarduipanel_prefab";
        public const string REWARDUIPANEL = "rewarduipanel";
    }
    public class Sceneres_unity
    {
        public const string BundleName = "sceneres_unity";
        public const string SCENERES = "sceneres";
    }
    public class Shopbuyui_prefab
    {
        public const string BundleName = "shopbuyui_prefab";
        public const string SHOPBUYUI = "shopbuyui";
    }
    public class Shopenhanceui_prefab
    {
        public const string BundleName = "shopenhanceui_prefab";
        public const string SHOPENHANCEUI = "shopenhanceui";
    }
    public class Shopmainui_prefab
    {
        public const string BundleName = "shopmainui_prefab";
        public const string SHOPMAINUI = "shopmainui";
    }
    public class Shopsellui_prefab
    {
        public const string BundleName = "shopsellui_prefab";
        public const string SHOPSELLUI = "shopsellui";
    }
    public class Skill_infopanel_prefab
    {
        public const string BundleName = "skill_infopanel_prefab";
        public const string SKILL_INFOPANEL = "skill_infopanel";
    }
    public class Spriteatlas_spriteatlas
    {
        public const string BundleName = "spriteatlas_spriteatlas";
        public const string SPRITEATLAS = "spriteatlas";
    }
    public class Textureexample1_png
    {
        public const string BundleName = "textureexample1_png";
        public const string TEXTUREEXAMPLE1 = "textureexample1";
    }
    public class Uiabilitypanel_prefab
    {
        public const string BundleName = "uiabilitypanel_prefab";
        public const string UIABILITYPANEL = "uiabilitypanel";
    }
    public class Uibasicpanel_prefab
    {
        public const string BundleName = "uibasicpanel_prefab";
        public const string UIBASICPANEL = "uibasicpanel";
    }
    public class Uicardrewardpanel_prefab
    {
        public const string BundleName = "uicardrewardpanel_prefab";
        public const string UICARDREWARDPANEL = "uicardrewardpanel";
    }
    public class Uiconsolepanel_prefab
    {
        public const string BundleName = "uiconsolepanel_prefab";
        public const string UICONSOLEPANEL = "uiconsolepanel";
    }
    public class Uiexplore_prefab
    {
        public const string BundleName = "uiexplore_prefab";
        public const string UIEXPLORE = "uiexplore";
    }
    public class Uihandcard_prefab
    {
        public const string BundleName = "uihandcard_prefab";
        public const string UIHANDCARD = "uihandcard";
    }
    public class Uiinventoryquickslot_prefab
    {
        public const string BundleName = "uiinventoryquickslot_prefab";
        public const string UIINVENTORYQUICKSLOT = "uiinventoryquickslot";
    }
    public class Uimultipanel_prefab
    {
        public const string BundleName = "uimultipanel_prefab";
        public const string UIMULTIPANEL = "uimultipanel";
    }
    public class Uiopenpackpanel_prefab
    {
        public const string BundleName = "uiopenpackpanel_prefab";
        public const string UIOPENPACKPANEL = "uiopenpackpanel";
    }
    public class Uipanelwithimageprefab_prefab
    {
        public const string BundleName = "uipanelwithimageprefab_prefab";
        public const string UIPANELWITHIMAGEPREFAB = "uipanelwithimageprefab";
    }
    public class Uirelic_prefab
    {
        public const string BundleName = "uirelic_prefab";
        public const string UIRELIC = "uirelic";
    }
    public class Uistackpanel1_prefab
    {
        public const string BundleName = "uistackpanel1_prefab";
        public const string UISTACKPANEL1 = "uistackpanel1";
    }
    public class Uistackpanel2_prefab
    {
        public const string BundleName = "uistackpanel2_prefab";
        public const string UISTACKPANEL2 = "uistackpanel2";
    }
}
