//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace cfg.GameData
{ 
    public enum CardPack
    {
        /// <summary>
        /// 无
        /// </summary>
        None = 0,
        /// <summary>
        /// 基础包
        /// </summary>
        Base = 1,
        /// <summary>
        /// 战士包
        /// </summary>
        Warrior = 2,
    }

} 
