//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace cfg.GameData
{ 
    public enum MoveDir
    {
        /// <summary>
        /// 无
        /// </summary>
        None = 0,
        /// <summary>
        /// 上
        /// </summary>
        Top = 1,
        /// <summary>
        /// 右
        /// </summary>
        Right = 2,
        /// <summary>
        /// 下
        /// </summary>
        Down = 3,
        /// <summary>
        /// 左
        /// </summary>
        Left = 4,
        /// <summary>
        /// 左上
        /// </summary>
        Topeft = 5,
        /// <summary>
        /// 右上
        /// </summary>
        Topright = 6,
        /// <summary>
        /// 右下
        /// </summary>
        Downright = 7,
        /// <summary>
        /// 左下
        /// </summary>
        Downleft = 8,
    }

} 
