//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace cfg.GameData
{ 
    public enum PlayerStats
    {
        /// <summary>
        /// 无
        /// </summary>
        None = 0,
        /// <summary>
        /// 力量
        /// </summary>
        Strength = 1,
        /// <summary>
        /// 精神
        /// </summary>
        Spirit = 2,
        /// <summary>
        /// 技巧
        /// </summary>
        Skill = 3,
        /// <summary>
        /// 体质
        /// </summary>
        Stamina = 4,
        /// <summary>
        /// 魅力
        /// </summary>
        Charisma = 5,
        /// <summary>
        /// 五围
        /// </summary>
        Total = 6,
    }

} 
