//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace cfg.GameData
{ 

/// <summary>
/// 玩家属性乘以倍数，加在初始数值上
/// </summary>
public sealed partial class PlayerBonus :  Bright.Config.BeanBase 
{
    public PlayerBonus(JSONNode _json) 
    {
        { if(!_json["property"].IsNumber) { throw new SerializationException(); }  Property = (GameData.PlayerStats)_json["property"].AsInt; }
        { if(!_json["multiple"].IsNumber) { throw new SerializationException(); }  Multiple = _json["multiple"]; }
        PostInit();
    }

    public PlayerBonus(GameData.PlayerStats property, float multiple ) 
    {
        this.Property = property;
        this.Multiple = multiple;
        PostInit();
    }

    public static PlayerBonus DeserializePlayerBonus(JSONNode _json)
    {
        return new GameData.PlayerBonus(_json);
    }

    /// <summary>
    /// 属性
    /// </summary>
    public GameData.PlayerStats Property { get; private set; }
    /// <summary>
    /// 倍数
    /// </summary>
    public float Multiple { get; private set; }

    public const int __ID__ = 1149893004;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Property:" + Property + ","
        + "Multiple:" + Multiple + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}
