//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace cfg.GameData
{ 

public sealed partial class TbRelic
{
    private readonly Dictionary<int, GameData.Relic> _dataMap;
    private readonly List<GameData.Relic> _dataList;
    
    public TbRelic(JSONNode _json)
    {
        _dataMap = new Dictionary<int, GameData.Relic>();
        _dataList = new List<GameData.Relic>();
        
        foreach(JSONNode _row in _json.Children)
        {
            var _v = GameData.Relic.DeserializeRelic(_row);
            _dataList.Add(_v);
            _dataMap.Add(_v.RelicID, _v);
        }
        PostInit();
    }

    public Dictionary<int, GameData.Relic> DataMap => _dataMap;
    public List<GameData.Relic> DataList => _dataList;

    public GameData.Relic GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public GameData.Relic Get(int key) => _dataMap[key];
    public GameData.Relic this[int key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    
    partial void PostInit();
    partial void PostResolve();
}

}